"""
Flumy simulation wrapper for generating channelized reservoir facies models.

Wraps the flumy Python package (https://flumy.minesparis.psl.eu/) to produce
3D facies blocks and extract 2D plan-view slices for training data generation.

Facies classification (CHANNELASSO_AV, 6 classes):
    0: Overbank  — floodplain/shale
    1: Channel   — channel lag, point bar, abandoned channel
    2: Levee     — natural levee
    3: Cravasse  — crevasse splay
    4: Coal      — coal (not generated by Flumy; reserved)
    5: Others    — undefined/other
"""

import numpy as np

# CHANNELASSO_AV encoding (6 classes)
FACIES_OVERBANK = 0
FACIES_CHANNEL = 1
FACIES_LEVEE = 2
FACIES_CRAVASSE = 3
FACIES_COAL = 4
FACIES_OTHERS = 5

FACIES_NAMES = {
    FACIES_OVERBANK: "overbank",
    FACIES_CHANNEL: "channel",
    FACIES_LEVEE: "levee",
    FACIES_CRAVASSE: "cravasse",
    FACIES_COAL: "coal",
    FACIES_OTHERS: "others",
}

# Evenly spaced normalized values in [-1, 1]
FACIES_NORMALIZED = {
    FACIES_OVERBANK: -1.0,
    FACIES_CHANNEL: -0.6,
    FACIES_LEVEE:   -0.2,
    FACIES_CRAVASSE: 0.2,
    FACIES_COAL:     0.6,
    FACIES_OTHERS:   1.0,
}

# LITHO_FLUMY_AV encoding (3 classes)
LITHO_SHALE = 0
LITHO_SAND = 1
LITHO_SILT = 2

LITHO_NAMES = {
    LITHO_SHALE: "shale",
    LITHO_SAND: "sand",
    LITHO_SILT: "silt",
}

LITHO_NORMALIZED = {
    LITHO_SHALE: -1.0,
    LITHO_SAND: 0.0,
    LITHO_SILT: 1.0,
}



class FlumyGenerator:
    """
    Generate channelized reservoir facies models using the flumy package.

    Produces 3D facies blocks and extracts 2D plan-view slices for training
    data generation. Each simulation generates a unique realization using
    a different random seed.

    NOTE: it is better to fix nx, ny to some multiple of 64 (e.g. 256) to ensure compatibility with common CNN architectures.
    Varying the mesh size according to channel width introduces complexity in the training pipeline. Some channels geting cropped
    out should not be a problem as long as the training data is sufficiently diverse.

    Args:
        nx: Number of grid nodes along x-axis
        ny: Number of grid nodes along y-axis
        mesh: Horizontal grid mesh size in meters
        hmax: Maximum channel depth in meters
        ng: Target net-to-gross ratio (0-100)
        isbx: Sand body extension parameter (controls cutoff frequency)
        zul: Total reservoir height to fill in meters (default: 3 * hmax)
        dz: Vertical discretization step in meters (default: 1)
        verbose: Whether to print simulation progress
    """

    def __init__(
        self,
        nx=256,
        ny=256,
        mesh=20,
        hmax=3.0,
        ng=50,
        isbx=80,
        zul=None,
        dz=1,
        verbose=False,
    ):
        self.nx = nx
        self.ny = ny
        self.mesh = mesh
        self.hmax = hmax
        self.ng = ng
        self.isbx = isbx
        self.zul = zul or 3 * hmax
        self.dz = dz
        self.nz = int(self.zul / self.dz)
        self.verbose = verbose

    def generate(self, seed):
        """
        Run a single Flumy simulation and return the 3D facies block.

        Args:
            seed: Random seed for reproducibility

        Returns:
            facies_block: np.ndarray of shape (nx, ny, nz) with facies codes
                         {0: mud, 1: bank, 2: sand}
        """
        from flumy import Flumy

        flsim = Flumy(self.nx, self.ny, self.mesh, self.verbose)
        success = flsim.launch(seed, self.hmax, self.isbx, self.ng, self.zul)
        if not success:
            raise RuntimeError(f"Flumy simulation failed with seed={seed}")

        facies_raw, _, _ = flsim.getBlock(self.dz, zb=0, nz=self.nz)

        return facies_raw.astype(np.int8)

    @staticmethod
    def reclassify_facies(facies_raw):
        """
        Reclassify Flumy's internal facies codes (0-13) to CHANNELASSO_AV (0-5).

        Flumy raw codes:
            0:Undefined, 1:Channel Lag, 2:Point Bar/LAPs, 3:Sand Plug,
            4:Crevasse Splay I, 5:Crev.Spl.Channel, 6:Crevasse Splay II,
            7:Levee, 8:Overbank, 9:Mud Plug, 10:Hemipelagic Plug,
            11:Wetland, 12:Draping, 13:Pelagic

        CHANNELASSO_AV mapping:
            Channel (1):  CL(1), PB(2), SP(3)  — channel lag, point bar, abandoned channel
            Cravasse (3): CS1(4), CCH(5), CS2(6)
            Levee (2):    LV(7)
            Overbank (0): all others (0,8,9,10,11,12,13)
        """
        # Default: overbank
        facies = np.full(facies_raw.shape, FACIES_OVERBANK, dtype=np.int8)

        # Channel: channel lag (1), point bar (2), sand plug/abandoned channel (3)
        facies[(facies_raw == 1) | (facies_raw == 2) | (facies_raw == 3)] = FACIES_CHANNEL

        # Cravasse: crevasse splay I (4), crev. spl. channel (5), crevasse splay II (6)
        facies[(facies_raw == 4) | (facies_raw == 5) | (facies_raw == 6)] = FACIES_CRAVASSE

        # Levee: natural levee (7)
        facies[facies_raw == 7] = FACIES_LEVEE

        return facies

    @staticmethod
    def reclassify_to_three_facies(facies_raw):
        """Deprecated: use reclassify_facies() instead."""
        return FlumyGenerator.reclassify_facies(facies_raw)


def normalize_facies(facies_map):
    """
    Normalize integer facies codes to [-1, 1] range.

    Args:
        facies_map: 2D array with values {0: bank, 1: channel, 2: point_bar}

    Returns:
        Normalized array with values {-1.0: bank, 0.0: channel, 1.0: point_bar}
    """
    normalized = np.zeros_like(facies_map, dtype=np.float32)
    for code, value in FACIES_NORMALIZED.items():
        normalized[facies_map == code] = value
    return normalized


def map_channelasso_to_litho(facies_channelasso):
    """Map CHANNELASSO_AV (0-5) to LITHO_FLUMY_AV (0-2).

    Mapping:
        - Channel (1), Cravasse (3) -> Sand (1)
        - Levee (2) -> Silt (2)
        - Overbank (0), Coal (4), Others (5) -> Shale (0)
    """
    litho = np.full(facies_channelasso.shape, LITHO_SHALE, dtype=np.int8)
    litho[(facies_channelasso == FACIES_CHANNEL) | (facies_channelasso == FACIES_CRAVASSE)] = LITHO_SAND
    litho[facies_channelasso == FACIES_LEVEE] = LITHO_SILT
    return litho


def normalize_lithofacies(litho_map):
    """Normalize 3-class lithofacies to [-1, 1] expected by diffusion training."""
    normalized = np.zeros_like(litho_map, dtype=np.float32)
    for code, value in LITHO_NORMALIZED.items():
        normalized[litho_map == code] = value
    return normalized


def denormalize_lithofacies(normalized_map):
    """Convert normalized values back to 3-class lithofacies integer codes."""
    values = np.array(list(LITHO_NORMALIZED.values()))
    codes = np.array(list(LITHO_NORMALIZED.keys()))
    distances = np.abs(
        normalized_map[..., np.newaxis] - values[np.newaxis, np.newaxis, :]
    )
    closest = np.argmin(distances, axis=-1)
    return codes[closest].astype(np.int8)


def denormalize_facies(normalized_map):
    """
    Convert normalized facies values back to integer codes.

    Args:
        normalized_map: Array with continuous values, will be rounded to nearest facies

    Returns:
        Integer array with values {0, 1, 2}
    """
    values = np.array(list(FACIES_NORMALIZED.values()))
    codes = np.array(list(FACIES_NORMALIZED.keys()))

    distances = np.abs(
        normalized_map[..., np.newaxis] - values[np.newaxis, np.newaxis, :]
    )
    closest = np.argmin(distances, axis=-1)
    return codes[closest].astype(np.int8)
